date.timezone = Europe/Rome
memory_limit = 256M
max_execution_time = 300
post_max_size = 32M
upload_max_filesize = 32M
display_errors = Off
error_reporting = E_ALL
display_startup_errors = Off
log_errors = On
error_log = /proc/self/fd/2
expose_php = Off
