name: astrolab

services:

  astrolab-web:
    build: .
    container_name: astrolab-web
    restart: unless-stopped
    ports:
      - "8090:80"
    volumes:
      - ./www:/var/www/html
      - ./php-config/php.ini:/usr/local/etc/php/php.ini
    env_file:
      - .env
    environment:
      - TZ=Europe/Rome
    depends_on:
      - astrolab-db
    networks:
      - astrolab-net

  astrolab-db:
    image: postgres:16-alpine
    container_name: astrolab-db
    restart: unless-stopped
    ports:
      - "5440:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - TZ=Europe/Rome
    networks:
      - astrolab-net

  astrolab-adminer:
    image: adminer:latest
    container_name: astrolab-adminer
    restart: unless-stopped
    ports:
      - "8091:8080"
    environment:
      - TZ=Europe/Rome
    depends_on:
      - astrolab-db
    networks:
      - astrolab-net

networks:
  astrolab-net:
    driver: bridge
