-- 013_diario_rsm.sql
-- Blocco C, Fase 1 - docs/roadmaps/ROADMAP_DIARIO_RSM.md (D1-D19)
-- Diario RSM: viaggi privati, contributi condivisi per localita', tratte, e tabelle
-- di riferimento delle nazioni (nomi italiani CLDR, D18) e dei territori (D19).

BEGIN;

SET search_path = public;

-- Nazioni: il codice ISO resta interno, l'interfaccia mostra sempre nome_it (D18).
-- Nomi italiani e inglesi dai dati CLDR (Unicode); alias = altri nomi cercabili.
CREATE TABLE nazioni (
    iso      CHAR(2) PRIMARY KEY,
    nome_it  VARCHAR(100) NOT NULL,
    nome_en  VARCHAR(100) NOT NULL,
    alias    TEXT[] NOT NULL DEFAULT '{}',
    CONSTRAINT nazioni_iso_check CHECK (iso ~ '^[A-Z]{2}$')
);

CREATE INDEX idx_nazioni_nome_it_trgm ON nazioni USING gin (nome_it gin_trgm_ops);
CREATE INDEX idx_nazioni_nome_en_trgm ON nazioni USING gin (nome_en gin_trgm_ops);

INSERT INTO nazioni (iso, nome_it, nome_en, alias) VALUES
    ('AD', 'Andorra', 'Andorra', '{}'::TEXT[]),
    ('AE', 'Emirati Arabi Uniti', 'United Arab Emirates', '{}'::TEXT[]),
    ('AF', 'Afghanistan', 'Afghanistan', '{}'::TEXT[]),
    ('AG', 'Antigua e Barbuda', 'Antigua & Barbuda', '{}'::TEXT[]),
    ('AI', 'Anguilla', 'Anguilla', '{}'::TEXT[]),
    ('AL', 'Albania', 'Albania', '{}'::TEXT[]),
    ('AM', 'Armenia', 'Armenia', '{}'::TEXT[]),
    ('AO', 'Angola', 'Angola', '{}'::TEXT[]),
    ('AQ', 'Antartide', 'Antarctica', '{}'::TEXT[]),
    ('AR', 'Argentina', 'Argentina', '{}'::TEXT[]),
    ('AS', 'Samoa Americane', 'American Samoa', '{}'::TEXT[]),
    ('AT', 'Austria', 'Austria', '{}'::TEXT[]),
    ('AU', 'Australia', 'Australia', '{}'::TEXT[]),
    ('AW', 'Aruba', 'Aruba', '{}'::TEXT[]),
    ('AX', 'Isole Åland', 'Åland Islands', '{}'::TEXT[]),
    ('AZ', 'Azerbaigian', 'Azerbaijan', '{}'::TEXT[]),
    ('BA', 'Bosnia ed Erzegovina', 'Bosnia & Herzegovina', '{}'::TEXT[]),
    ('BB', 'Barbados', 'Barbados', '{}'::TEXT[]),
    ('BD', 'Bangladesh', 'Bangladesh', '{}'::TEXT[]),
    ('BE', 'Belgio', 'Belgium', '{}'::TEXT[]),
    ('BF', 'Burkina Faso', 'Burkina Faso', '{}'::TEXT[]),
    ('BG', 'Bulgaria', 'Bulgaria', '{}'::TEXT[]),
    ('BH', 'Bahrein', 'Bahrain', '{}'::TEXT[]),
    ('BI', 'Burundi', 'Burundi', '{}'::TEXT[]),
    ('BJ', 'Benin', 'Benin', '{}'::TEXT[]),
    ('BL', 'Saint-Barthélemy', 'St. Barthélemy', '{}'::TEXT[]),
    ('BM', 'Bermuda', 'Bermuda', '{}'::TEXT[]),
    ('BN', 'Brunei', 'Brunei', '{}'::TEXT[]),
    ('BO', 'Bolivia', 'Bolivia', '{}'::TEXT[]),
    ('BQ', 'Caraibi Olandesi', 'Caribbean Netherlands', '{}'::TEXT[]),
    ('BR', 'Brasile', 'Brazil', '{}'::TEXT[]),
    ('BS', 'Bahamas', 'Bahamas', '{}'::TEXT[]),
    ('BT', 'Bhutan', 'Bhutan', '{}'::TEXT[]),
    ('BV', 'Isola Bouvet', 'Bouvet Island', '{}'::TEXT[]),
    ('BW', 'Botswana', 'Botswana', '{}'::TEXT[]),
    ('BY', 'Bielorussia', 'Belarus', '{}'::TEXT[]),
    ('BZ', 'Belize', 'Belize', '{}'::TEXT[]),
    ('CA', 'Canada', 'Canada', '{}'::TEXT[]),
    ('CC', 'Isole Cocos (Keeling)', 'Cocos (Keeling) Islands', '{}'::TEXT[]),
    ('CD', 'Congo - Kinshasa', 'Congo - Kinshasa', '{}'::TEXT[]),
    ('CF', 'Repubblica Centrafricana', 'Central African Republic', '{}'::TEXT[]),
    ('CG', 'Congo-Brazzaville', 'Congo - Brazzaville', '{}'::TEXT[]),
    ('CH', 'Svizzera', 'Switzerland', '{}'::TEXT[]),
    ('CI', 'Costa d’Avorio', 'Côte d’Ivoire', ARRAY['Costa d''Avorio']::TEXT[]),
    ('CK', 'Isole Cook', 'Cook Islands', '{}'::TEXT[]),
    ('CL', 'Cile', 'Chile', '{}'::TEXT[]),
    ('CM', 'Camerun', 'Cameroon', '{}'::TEXT[]),
    ('CN', 'Cina', 'China', '{}'::TEXT[]),
    ('CO', 'Colombia', 'Colombia', '{}'::TEXT[]),
    ('CR', 'Costa Rica', 'Costa Rica', '{}'::TEXT[]),
    ('CU', 'Cuba', 'Cuba', '{}'::TEXT[]),
    ('CV', 'Capo Verde', 'Cape Verde', '{}'::TEXT[]),
    ('CW', 'Curaçao', 'Curaçao', '{}'::TEXT[]),
    ('CX', 'Isola Christmas', 'Christmas Island', '{}'::TEXT[]),
    ('CY', 'Cipro', 'Cyprus', '{}'::TEXT[]),
    ('CZ', 'Cechia', 'Czechia', ARRAY['Repubblica Ceca']::TEXT[]),
    ('DE', 'Germania', 'Germany', '{}'::TEXT[]),
    ('DJ', 'Gibuti', 'Djibouti', '{}'::TEXT[]),
    ('DK', 'Danimarca', 'Denmark', '{}'::TEXT[]),
    ('DM', 'Dominica', 'Dominica', '{}'::TEXT[]),
    ('DO', 'Repubblica Dominicana', 'Dominican Republic', '{}'::TEXT[]),
    ('DZ', 'Algeria', 'Algeria', '{}'::TEXT[]),
    ('EC', 'Ecuador', 'Ecuador', '{}'::TEXT[]),
    ('EE', 'Estonia', 'Estonia', '{}'::TEXT[]),
    ('EG', 'Egitto', 'Egypt', '{}'::TEXT[]),
    ('EH', 'Sahara Occidentale', 'Western Sahara', '{}'::TEXT[]),
    ('ER', 'Eritrea', 'Eritrea', '{}'::TEXT[]),
    ('ES', 'Spagna', 'Spain', '{}'::TEXT[]),
    ('ET', 'Etiopia', 'Ethiopia', '{}'::TEXT[]),
    ('FI', 'Finlandia', 'Finland', '{}'::TEXT[]),
    ('FJ', 'Figi', 'Fiji', '{}'::TEXT[]),
    ('FK', 'Isole Falkland (Malvine)', 'Falkland Islands', ARRAY['Falkland', 'Malvine', 'Malvinas']::TEXT[]),
    ('FM', 'Micronesia', 'Micronesia', '{}'::TEXT[]),
    ('FO', 'Isole Fær Øer', 'Faroe Islands', '{}'::TEXT[]),
    ('FR', 'Francia', 'France', '{}'::TEXT[]),
    ('GA', 'Gabon', 'Gabon', '{}'::TEXT[]),
    ('GB', 'Regno Unito', 'United Kingdom', ARRAY['Inghilterra', 'Gran Bretagna', 'Scozia', 'Galles', 'Irlanda del Nord', 'UK']::TEXT[]),
    ('GD', 'Grenada', 'Grenada', '{}'::TEXT[]),
    ('GE', 'Georgia', 'Georgia', '{}'::TEXT[]),
    ('GF', 'Guyana Francese', 'French Guiana', '{}'::TEXT[]),
    ('GG', 'Guernsey', 'Guernsey', '{}'::TEXT[]),
    ('GH', 'Ghana', 'Ghana', '{}'::TEXT[]),
    ('GI', 'Gibilterra', 'Gibraltar', '{}'::TEXT[]),
    ('GL', 'Groenlandia', 'Greenland', '{}'::TEXT[]),
    ('GM', 'Gambia', 'Gambia', '{}'::TEXT[]),
    ('GN', 'Guinea', 'Guinea', '{}'::TEXT[]),
    ('GP', 'Guadalupa', 'Guadeloupe', '{}'::TEXT[]),
    ('GQ', 'Guinea Equatoriale', 'Equatorial Guinea', '{}'::TEXT[]),
    ('GR', 'Grecia', 'Greece', '{}'::TEXT[]),
    ('GS', 'Georgia del Sud e Sandwich Australi', 'South Georgia & South Sandwich Islands', '{}'::TEXT[]),
    ('GT', 'Guatemala', 'Guatemala', '{}'::TEXT[]),
    ('GU', 'Guam', 'Guam', '{}'::TEXT[]),
    ('GW', 'Guinea-Bissau', 'Guinea-Bissau', '{}'::TEXT[]),
    ('GY', 'Guyana', 'Guyana', '{}'::TEXT[]),
    ('HK', 'Hong Kong', 'Hong Kong SAR China', '{}'::TEXT[]),
    ('HM', 'Isole Heard e McDonald', 'Heard & McDonald Islands', '{}'::TEXT[]),
    ('HN', 'Honduras', 'Honduras', '{}'::TEXT[]),
    ('HR', 'Croazia', 'Croatia', '{}'::TEXT[]),
    ('HT', 'Haiti', 'Haiti', '{}'::TEXT[]),
    ('HU', 'Ungheria', 'Hungary', '{}'::TEXT[]),
    ('ID', 'Indonesia', 'Indonesia', '{}'::TEXT[]),
    ('IE', 'Irlanda', 'Ireland', '{}'::TEXT[]),
    ('IL', 'Israele', 'Israel', '{}'::TEXT[]),
    ('IM', 'Isola di Man', 'Isle of Man', '{}'::TEXT[]),
    ('IN', 'India', 'India', '{}'::TEXT[]),
    ('IO', 'Territorio Britannico dell’Oceano Indiano', 'British Indian Ocean Territory', '{}'::TEXT[]),
    ('IQ', 'Iraq', 'Iraq', '{}'::TEXT[]),
    ('IR', 'Iran', 'Iran', '{}'::TEXT[]),
    ('IS', 'Islanda', 'Iceland', '{}'::TEXT[]),
    ('IT', 'Italia', 'Italy', '{}'::TEXT[]),
    ('JE', 'Jersey', 'Jersey', '{}'::TEXT[]),
    ('JM', 'Giamaica', 'Jamaica', '{}'::TEXT[]),
    ('JO', 'Giordania', 'Jordan', '{}'::TEXT[]),
    ('JP', 'Giappone', 'Japan', '{}'::TEXT[]),
    ('KE', 'Kenya', 'Kenya', '{}'::TEXT[]),
    ('KG', 'Kirghizistan', 'Kyrgyzstan', '{}'::TEXT[]),
    ('KH', 'Cambogia', 'Cambodia', '{}'::TEXT[]),
    ('KI', 'Kiribati', 'Kiribati', '{}'::TEXT[]),
    ('KM', 'Comore', 'Comoros', '{}'::TEXT[]),
    ('KN', 'Saint Kitts e Nevis', 'St. Kitts & Nevis', '{}'::TEXT[]),
    ('KP', 'Corea del Nord', 'North Korea', '{}'::TEXT[]),
    ('KR', 'Corea del Sud', 'South Korea', ARRAY['Corea']::TEXT[]),
    ('KW', 'Kuwait', 'Kuwait', '{}'::TEXT[]),
    ('KY', 'Isole Cayman', 'Cayman Islands', '{}'::TEXT[]),
    ('KZ', 'Kazakistan', 'Kazakhstan', '{}'::TEXT[]),
    ('LA', 'Laos', 'Laos', '{}'::TEXT[]),
    ('LB', 'Libano', 'Lebanon', '{}'::TEXT[]),
    ('LC', 'Saint Lucia', 'St. Lucia', '{}'::TEXT[]),
    ('LI', 'Liechtenstein', 'Liechtenstein', '{}'::TEXT[]),
    ('LK', 'Sri Lanka', 'Sri Lanka', '{}'::TEXT[]),
    ('LR', 'Liberia', 'Liberia', '{}'::TEXT[]),
    ('LS', 'Lesotho', 'Lesotho', '{}'::TEXT[]),
    ('LT', 'Lituania', 'Lithuania', '{}'::TEXT[]),
    ('LU', 'Lussemburgo', 'Luxembourg', '{}'::TEXT[]),
    ('LV', 'Lettonia', 'Latvia', '{}'::TEXT[]),
    ('LY', 'Libia', 'Libya', '{}'::TEXT[]),
    ('MA', 'Marocco', 'Morocco', '{}'::TEXT[]),
    ('MC', 'Monaco', 'Monaco', '{}'::TEXT[]),
    ('MD', 'Moldavia', 'Moldova', '{}'::TEXT[]),
    ('ME', 'Montenegro', 'Montenegro', '{}'::TEXT[]),
    ('MF', 'Saint Martin', 'St. Martin', '{}'::TEXT[]),
    ('MG', 'Madagascar', 'Madagascar', '{}'::TEXT[]),
    ('MH', 'Isole Marshall', 'Marshall Islands', '{}'::TEXT[]),
    ('MK', 'Macedonia del Nord', 'North Macedonia', '{}'::TEXT[]),
    ('ML', 'Mali', 'Mali', '{}'::TEXT[]),
    ('MM', 'Myanmar (Birmania)', 'Myanmar (Burma)', ARRAY['Birmania']::TEXT[]),
    ('MN', 'Mongolia', 'Mongolia', '{}'::TEXT[]),
    ('MO', 'Macao', 'Macao SAR China', '{}'::TEXT[]),
    ('MP', 'Isole Marianne Settentrionali', 'Northern Mariana Islands', '{}'::TEXT[]),
    ('MQ', 'Martinica', 'Martinique', '{}'::TEXT[]),
    ('MR', 'Mauritania', 'Mauritania', '{}'::TEXT[]),
    ('MS', 'Montserrat', 'Montserrat', '{}'::TEXT[]),
    ('MT', 'Malta', 'Malta', '{}'::TEXT[]),
    ('MU', 'Mauritius', 'Mauritius', '{}'::TEXT[]),
    ('MV', 'Maldive', 'Maldives', '{}'::TEXT[]),
    ('MW', 'Malawi', 'Malawi', '{}'::TEXT[]),
    ('MX', 'Messico', 'Mexico', '{}'::TEXT[]),
    ('MY', 'Malaysia', 'Malaysia', '{}'::TEXT[]),
    ('MZ', 'Mozambico', 'Mozambique', '{}'::TEXT[]),
    ('NA', 'Namibia', 'Namibia', '{}'::TEXT[]),
    ('NC', 'Nuova Caledonia', 'New Caledonia', '{}'::TEXT[]),
    ('NE', 'Niger', 'Niger', '{}'::TEXT[]),
    ('NF', 'Isola Norfolk', 'Norfolk Island', '{}'::TEXT[]),
    ('NG', 'Nigeria', 'Nigeria', '{}'::TEXT[]),
    ('NI', 'Nicaragua', 'Nicaragua', '{}'::TEXT[]),
    ('NL', 'Paesi Bassi', 'Netherlands', ARRAY['Olanda']::TEXT[]),
    ('NO', 'Norvegia', 'Norway', '{}'::TEXT[]),
    ('NP', 'Nepal', 'Nepal', '{}'::TEXT[]),
    ('NR', 'Nauru', 'Nauru', '{}'::TEXT[]),
    ('NU', 'Niue', 'Niue', '{}'::TEXT[]),
    ('NZ', 'Nuova Zelanda', 'New Zealand', '{}'::TEXT[]),
    ('OM', 'Oman', 'Oman', '{}'::TEXT[]),
    ('PA', 'Panama', 'Panama', '{}'::TEXT[]),
    ('PE', 'Perù', 'Peru', '{}'::TEXT[]),
    ('PF', 'Polinesia Francese', 'French Polynesia', '{}'::TEXT[]),
    ('PG', 'Papua Nuova Guinea', 'Papua New Guinea', '{}'::TEXT[]),
    ('PH', 'Filippine', 'Philippines', '{}'::TEXT[]),
    ('PK', 'Pakistan', 'Pakistan', '{}'::TEXT[]),
    ('PL', 'Polonia', 'Poland', '{}'::TEXT[]),
    ('PM', 'Saint-Pierre e Miquelon', 'St. Pierre & Miquelon', '{}'::TEXT[]),
    ('PN', 'Isole Pitcairn', 'Pitcairn Islands', '{}'::TEXT[]),
    ('PR', 'Portorico', 'Puerto Rico', '{}'::TEXT[]),
    ('PS', 'Territori Palestinesi', 'Palestinian Territories', '{}'::TEXT[]),
    ('PT', 'Portogallo', 'Portugal', '{}'::TEXT[]),
    ('PW', 'Palau', 'Palau', '{}'::TEXT[]),
    ('PY', 'Paraguay', 'Paraguay', '{}'::TEXT[]),
    ('QA', 'Qatar', 'Qatar', '{}'::TEXT[]),
    ('RE', 'Riunione', 'Réunion', '{}'::TEXT[]),
    ('RO', 'Romania', 'Romania', '{}'::TEXT[]),
    ('RS', 'Serbia', 'Serbia', '{}'::TEXT[]),
    ('RU', 'Russia', 'Russia', ARRAY['Federazione Russa']::TEXT[]),
    ('RW', 'Ruanda', 'Rwanda', '{}'::TEXT[]),
    ('SA', 'Arabia Saudita', 'Saudi Arabia', '{}'::TEXT[]),
    ('SB', 'Isole Salomone', 'Solomon Islands', '{}'::TEXT[]),
    ('SC', 'Seychelles', 'Seychelles', '{}'::TEXT[]),
    ('SD', 'Sudan', 'Sudan', '{}'::TEXT[]),
    ('SE', 'Svezia', 'Sweden', '{}'::TEXT[]),
    ('SG', 'Singapore', 'Singapore', '{}'::TEXT[]),
    ('SH', 'Sant’Elena', 'St. Helena', '{}'::TEXT[]),
    ('SI', 'Slovenia', 'Slovenia', '{}'::TEXT[]),
    ('SJ', 'Svalbard e Jan Mayen', 'Svalbard & Jan Mayen', ARRAY['Svalbard', 'Jan Mayen']::TEXT[]),
    ('SK', 'Slovacchia', 'Slovakia', '{}'::TEXT[]),
    ('SL', 'Sierra Leone', 'Sierra Leone', '{}'::TEXT[]),
    ('SM', 'San Marino', 'San Marino', '{}'::TEXT[]),
    ('SN', 'Senegal', 'Senegal', '{}'::TEXT[]),
    ('SO', 'Somalia', 'Somalia', '{}'::TEXT[]),
    ('SR', 'Suriname', 'Suriname', '{}'::TEXT[]),
    ('SS', 'Sud Sudan', 'South Sudan', '{}'::TEXT[]),
    ('ST', 'São Tomé e Príncipe', 'São Tomé & Príncipe', '{}'::TEXT[]),
    ('SV', 'El Salvador', 'El Salvador', '{}'::TEXT[]),
    ('SX', 'Sint Maarten', 'Sint Maarten', '{}'::TEXT[]),
    ('SY', 'Siria', 'Syria', '{}'::TEXT[]),
    ('SZ', 'Eswatini', 'Eswatini', '{}'::TEXT[]),
    ('TC', 'Isole Turks e Caicos', 'Turks & Caicos Islands', '{}'::TEXT[]),
    ('TD', 'Ciad', 'Chad', '{}'::TEXT[]),
    ('TF', 'Terre Australi Francesi', 'French Southern Territories', '{}'::TEXT[]),
    ('TG', 'Togo', 'Togo', '{}'::TEXT[]),
    ('TH', 'Thailandia', 'Thailand', '{}'::TEXT[]),
    ('TJ', 'Tagikistan', 'Tajikistan', '{}'::TEXT[]),
    ('TK', 'Tokelau', 'Tokelau', '{}'::TEXT[]),
    ('TL', 'Timor Est', 'Timor-Leste', '{}'::TEXT[]),
    ('TM', 'Turkmenistan', 'Turkmenistan', '{}'::TEXT[]),
    ('TN', 'Tunisia', 'Tunisia', '{}'::TEXT[]),
    ('TO', 'Tonga', 'Tonga', '{}'::TEXT[]),
    ('TR', 'Turchia', 'Türkiye', '{}'::TEXT[]),
    ('TT', 'Trinidad e Tobago', 'Trinidad & Tobago', '{}'::TEXT[]),
    ('TV', 'Tuvalu', 'Tuvalu', '{}'::TEXT[]),
    ('TW', 'Taiwan', 'Taiwan', '{}'::TEXT[]),
    ('TZ', 'Tanzania', 'Tanzania', '{}'::TEXT[]),
    ('UA', 'Ucraina', 'Ukraine', '{}'::TEXT[]),
    ('UG', 'Uganda', 'Uganda', '{}'::TEXT[]),
    ('UM', 'Isole Minori Esterne degli Stati Uniti', 'U.S. Outlying Islands', '{}'::TEXT[]),
    ('US', 'Stati Uniti', 'United States', ARRAY['USA', 'America', 'Stati Uniti d’America']::TEXT[]),
    ('UY', 'Uruguay', 'Uruguay', '{}'::TEXT[]),
    ('UZ', 'Uzbekistan', 'Uzbekistan', '{}'::TEXT[]),
    ('VA', 'Città del Vaticano', 'Vatican City', ARRAY['Vaticano', 'Santa Sede']::TEXT[]),
    ('VC', 'Saint Vincent e Grenadine', 'St. Vincent & Grenadines', '{}'::TEXT[]),
    ('VE', 'Venezuela', 'Venezuela', '{}'::TEXT[]),
    ('VG', 'Isole Vergini Britanniche', 'British Virgin Islands', '{}'::TEXT[]),
    ('VI', 'Isole Vergini Americane', 'U.S. Virgin Islands', '{}'::TEXT[]),
    ('VN', 'Vietnam', 'Vietnam', '{}'::TEXT[]),
    ('VU', 'Vanuatu', 'Vanuatu', '{}'::TEXT[]),
    ('WF', 'Wallis e Futuna', 'Wallis & Futuna', '{}'::TEXT[]),
    ('WS', 'Samoa', 'Samoa', '{}'::TEXT[]),
    ('XK', 'Kosovo', 'Kosovo', '{}'::TEXT[]),
    ('YE', 'Yemen', 'Yemen', '{}'::TEXT[]),
    ('YT', 'Mayotte', 'Mayotte', '{}'::TEXT[]),
    ('ZA', 'Sudafrica', 'South Africa', '{}'::TEXT[]),
    ('ZM', 'Zambia', 'Zambia', '{}'::TEXT[]),
    ('ZW', 'Zimbabwe', 'Zimbabwe', '{}'::TEXT[]);

-- Territori con codice proprio che compaiono anche sotto la nazione indicata (D19).
CREATE TABLE nazioni_appartenenza (
    iso_territorio  CHAR(2) NOT NULL REFERENCES nazioni(iso),
    iso_nazione     CHAR(2) NOT NULL REFERENCES nazioni(iso),
    PRIMARY KEY (iso_territorio, iso_nazione),
    CONSTRAINT nazioni_appartenenza_diverse_check CHECK (iso_territorio <> iso_nazione)
);

INSERT INTO nazioni_appartenenza (iso_territorio, iso_nazione) VALUES
    ('SJ', 'NO'),
    ('BV', 'NO'),
    ('GL', 'DK'),
    ('FO', 'DK'),
    ('PF', 'FR'),
    ('NC', 'FR'),
    ('GF', 'FR'),
    ('GP', 'FR'),
    ('MQ', 'FR'),
    ('RE', 'FR'),
    ('YT', 'FR'),
    ('PM', 'FR'),
    ('BL', 'FR'),
    ('MF', 'FR'),
    ('WF', 'FR'),
    ('TF', 'FR'),
    ('FK', 'GB'),
    ('GI', 'GB'),
    ('GG', 'GB'),
    ('JE', 'GB'),
    ('IM', 'GB'),
    ('BM', 'GB'),
    ('KY', 'GB'),
    ('VG', 'GB'),
    ('TC', 'GB'),
    ('MS', 'GB'),
    ('AI', 'GB'),
    ('SH', 'GB'),
    ('PN', 'GB'),
    ('IO', 'GB'),
    ('GS', 'GB'),
    ('FK', 'AR'),
    ('GS', 'AR'),
    ('PR', 'US'),
    ('GU', 'US'),
    ('VI', 'US'),
    ('AS', 'US'),
    ('MP', 'US'),
    ('UM', 'US'),
    ('AW', 'NL'),
    ('CW', 'NL'),
    ('SX', 'NL'),
    ('BQ', 'NL'),
    ('CX', 'AU'),
    ('CC', 'AU'),
    ('NF', 'AU'),
    ('HM', 'AU'),
    ('TK', 'NZ'),
    ('CK', 'NZ'),
    ('NU', 'NZ'),
    ('HK', 'CN'),
    ('MO', 'CN'),
    ('AX', 'FI');

-- Viaggi RSM (privati): del soggetto o dell'astrologo, mai di entrambi (D14, D15).
CREATE TABLE viaggi_rsm (
    id               BIGSERIAL PRIMARY KEY,
    utente_id        INTEGER REFERENCES utenti(id) ON DELETE CASCADE,
    soggetto_id      INTEGER REFERENCES soggetti(id) ON DELETE CASCADE,
    sessione_rs_id   INTEGER REFERENCES sessioni_rs(id) ON DELETE SET NULL,
    luogo            VARCHAR(200) NOT NULL,
    iso_nazione      CHAR(2) NOT NULL REFERENCES nazioni(iso),
    latitudine       NUMERIC(9,6),
    longitudine      NUMERIC(9,6),
    data_arrivo      DATE,
    data_partenza    DATE,
    albergo          VARCHAR(200),
    costo_alloggio   NUMERIC(10,2),
    costo_trasporti  NUMERIC(10,2),
    valuta           CHAR(3) NOT NULL DEFAULT 'EUR',
    trasporti        TEXT,
    note_private     TEXT,
    creato_il        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    aggiornato_il    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT viaggi_rsm_autore_check CHECK ((utente_id IS NULL) <> (soggetto_id IS NULL)),
    CONSTRAINT viaggi_rsm_luogo_check CHECK (luogo = btrim(luogo) AND luogo <> ''),
    CONSTRAINT viaggi_rsm_date_check CHECK (data_partenza IS NULL OR data_arrivo IS NULL OR data_partenza >= data_arrivo),
    CONSTRAINT viaggi_rsm_costi_check CHECK (COALESCE(costo_alloggio, 0) >= 0 AND COALESCE(costo_trasporti, 0) >= 0),
    CONSTRAINT viaggi_rsm_valuta_check CHECK (valuta ~ '^[A-Z]{3}$'),
    CONSTRAINT viaggi_rsm_testi_check CHECK (COALESCE(char_length(trasporti), 0) <= 4000 AND COALESCE(char_length(note_private), 0) <= 4000)
);

CREATE INDEX idx_viaggi_rsm_utente ON viaggi_rsm (utente_id);
CREATE INDEX idx_viaggi_rsm_soggetto ON viaggi_rsm (soggetto_id);

-- Contributi condivisi: solo dati di viaggio, mai dati del soggetto (regola del par. 2).
-- Solo anno e mese del viaggio (D4). luogo_chiave raggruppa per nome normalizzato (D11).
CREATE TABLE contributi_localita (
    id                          BIGSERIAL PRIMARY KEY,
    utente_id                   INTEGER REFERENCES utenti(id) ON DELETE SET NULL,
    soggetto_id                 INTEGER REFERENCES soggetti(id) ON DELETE SET NULL,
    luogo                       VARCHAR(200) NOT NULL,
    luogo_chiave                VARCHAR(200) GENERATED ALWAYS AS (lower(regexp_replace(btrim(luogo), '\s+', ' ', 'g'))) STORED,
    iso_nazione                 CHAR(2) NOT NULL REFERENCES nazioni(iso),
    latitudine                  NUMERIC(9,6),
    longitudine                 NUMERIC(9,6),
    anno_viaggio                SMALLINT NOT NULL,
    mese_viaggio                SMALLINT,
    alloggio_nome               VARCHAR(200),
    alloggio_tipo               VARCHAR(20),
    alloggio_sito               VARCHAR(500),
    alloggio_fascia_prezzo      VARCHAR(50),
    alloggio_giudizio           TEXT,
    costo_alloggio_indicativo   NUMERIC(10,2),
    costo_alloggio_riferimento  VARCHAR(50),
    valuta                      CHAR(3) NOT NULL DEFAULT 'EUR',
    info_documenti              TEXT,
    info_clima                  TEXT,
    info_lingua_valuta          TEXT,
    info_connettivita           TEXT,
    info_particolarita          TEXT,
    contatti_utili              TEXT,
    consigli                    TEXT,
    dichiarazione_contatti      BOOLEAN NOT NULL,
    visibile                    BOOLEAN NOT NULL DEFAULT TRUE,
    creato_il                   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    aggiornato_il               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT contributi_autore_check CHECK (utente_id IS NULL OR soggetto_id IS NULL),
    CONSTRAINT contributi_luogo_check CHECK (luogo = btrim(luogo) AND luogo <> ''),
    CONSTRAINT contributi_anno_check CHECK (anno_viaggio BETWEEN 1900 AND 2100),
    CONSTRAINT contributi_mese_check CHECK (mese_viaggio IS NULL OR mese_viaggio BETWEEN 1 AND 12),
    CONSTRAINT contributi_alloggio_tipo_check CHECK (alloggio_tipo IS NULL OR alloggio_tipo IN
        ('hotel', 'bb', 'appartamento', 'guesthouse', 'campeggio', 'altro')),
    CONSTRAINT contributi_alloggio_sito_check CHECK (alloggio_sito IS NULL OR alloggio_sito ~* '^https?://'),
    CONSTRAINT contributi_costo_check CHECK (COALESCE(costo_alloggio_indicativo, 0) >= 0),
    CONSTRAINT contributi_valuta_check CHECK (valuta ~ '^[A-Z]{3}$'),
    CONSTRAINT contributi_dichiarazione_check CHECK (dichiarazione_contatti),
    CONSTRAINT contributi_testi_check CHECK (
        COALESCE(char_length(alloggio_giudizio), 0) <= 4000 AND
        COALESCE(char_length(info_documenti), 0) <= 4000 AND
        COALESCE(char_length(info_clima), 0) <= 4000 AND
        COALESCE(char_length(info_lingua_valuta), 0) <= 4000 AND
        COALESCE(char_length(info_connettivita), 0) <= 4000 AND
        COALESCE(char_length(info_particolarita), 0) <= 4000 AND
        COALESCE(char_length(contatti_utili), 0) <= 4000 AND
        COALESCE(char_length(consigli), 0) <= 4000)
);

CREATE INDEX idx_contributi_scheda ON contributi_localita (iso_nazione, luogo_chiave) WHERE visibile;
CREATE INDEX idx_contributi_luogo_trgm ON contributi_localita USING gin (luogo gin_trgm_ops);
CREATE INDEX idx_contributi_utente ON contributi_localita (utente_id);
CREATE INDEX idx_contributi_soggetto ON contributi_localita (soggetto_id);

-- Tratte del viaggio di un contributo (D6).
CREATE TABLE contributi_tratte (
    id                 BIGSERIAL PRIMARY KEY,
    contributo_id      BIGINT NOT NULL REFERENCES contributi_localita(id) ON DELETE CASCADE,
    ordine             SMALLINT NOT NULL,
    mezzo              VARCHAR(10) NOT NULL,
    da_luogo           VARCHAR(200),
    a_luogo            VARCHAR(200),
    compagnia          VARCHAR(150),
    durata_indicativa  VARCHAR(50),
    costo_indicativo   NUMERIC(10,2),
    valuta             CHAR(3) NOT NULL DEFAULT 'EUR',
    note               TEXT,
    CONSTRAINT contributi_tratte_ordine_unico UNIQUE (contributo_id, ordine),
    CONSTRAINT contributi_tratte_ordine_check CHECK (ordine BETWEEN 1 AND 15),
    CONSTRAINT contributi_tratte_mezzo_check CHECK (mezzo IN ('aereo', 'nave', 'treno', 'bus', 'auto', 'altro')),
    CONSTRAINT contributi_tratte_costo_check CHECK (COALESCE(costo_indicativo, 0) >= 0),
    CONSTRAINT contributi_tratte_valuta_check CHECK (valuta ~ '^[A-Z]{3}$'),
    CONSTRAINT contributi_tratte_note_check CHECK (COALESCE(char_length(note), 0) <= 2000)
);

COMMIT;
